name: Site Build
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # even minor npm version differences can lead to problems
          # with the same package-lock.json, so pin the minor version
          # (next up - same comment but with patch version 🤡)
          node-version: '18.4'
      - name: print versions
        run: |
          node -v
          npm -v
      - name: cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-npm-folder
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        # this used to be `npm ci` (https://stackoverflow.com/a/53325242/2525313),
        # but then that started to fail because of an error in package-lock.json,
        # even locally after just creating it!
        run: npm install
      - name: build with Gatsby
        run: npx gatsby build
